Replace
First Replace

diff --git a/deb/kaltura-batch/debian/postinst b/deb/kaltura-batch/debian/postinst
--- a/deb/kaltura-batch/debian/postinst
+++ b/deb/kaltura-batch/debian/postinst
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-KALTURA_FUNCTIONS_RC=/opt/kaltura/bin/kaltura-functions.rc
-if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
-        OUT="${BRIGHT_RED}ERROR:could not find $KALTURA_FUNCTIONS_RC so, exiting..${NORMAL}"
+BORHAN_FUNCTIONS_RC=/opt/borhan/bin/borhan-functions.rc
+if [ ! -r "$BORHAN_FUNCTIONS_RC" ];then
+        OUT="${BRIGHT_RED}ERROR:could not find $BORHAN_FUNCTIONS_RC so, exiting..${NORMAL}"
         echo -en $OUT
         exit 3
 fi
 
-RC_FILE=/etc/kaltura.d/system.ini
+RC_FILE=/etc/borhan.d/system.ini
 if [ ! -r "$RC_FILE" ];then
 	echo -e "${BRIGHT_RED}ERROR: could not find $RC_FILE so, exiting..${NORMAL}"
 	exit 1 
@@ -15,14 +15,14 @@ fi
 . $RC_FILE
 
 
-. $KALTURA_FUNCTIONS_RC
+. $BORHAN_FUNCTIONS_RC
 if [ "$1" = "configure" ];then
-	update-rc.d kaltura-batch defaults || true
+	update-rc.d borhan-batch defaults || true
 fi
-KALTURA_PREFIX=/opt/kaltura
-APP_DIR=/opt/kaltura/app
-KALTURA_GROUP=kaltura
-KALTURA_USER=kaltura
+BORHAN_PREFIX=/opt/borhan
+APP_DIR=/opt/borhan/app
+BORHAN_GROUP=borhan
+BORHAN_USER=borhan
 APACHE_USER=www-data
 APACHE_GROUP=www-data
 if [ -r $CONSENT_FILE ];then
@@ -34,7 +34,7 @@ fi
 trap 'my_trap_handler "${LINENO}" ${$?}' ERR
 TIMEZ=`get_tz`
 send_install_becon `basename $0` $TIMEZ install_start 0 
-CONFIG_DIR=/opt/kaltura/app/configurations
+CONFIG_DIR=/opt/borhan/app/configurations
 if [ -r $CONFIG_DIR/system.ini ];then
 	. $CONFIG_DIR/system.ini
 else
@@ -47,7 +47,7 @@ BATCH_MAIN_CONF=$APP_DIR/configurations/batch/batch.ini
 # if we couldn't access the DB to retrieve the secret, assume the post install has not finished yet.
 BATCH_PARTNER_ADMIN_SECRET=`echo "select admin_secret from partner where id=-1"|mysql -N -h$DB1_HOST -u$DB1_USER -p$DB1_PASS $DB1_NAME -P$DWH_PORT`
 if [ -z "$BATCH_PARTNER_ADMIN_SECRET" ];then
-	echo -e "${BRIGHT_RED}ERROR: could not retreive partner.admin_secret for id -1. It probably means you did not yet run $APP_DIR/kaltura-base-config.sh yet. Please do.${NORMAL}" 
+	echo -e "${BRIGHT_RED}ERROR: could not retreive partner.admin_secret for id -1. It probably means you did not yet run $APP_DIR/borhan-base-config.sh yet. Please do.${NORMAL}" 
 	exit 2
 fi
 
@@ -59,20 +59,20 @@ sed "s#@BATCH_SCHEDULER_ID@#$BATCH_SCHEDULER_ID#"  -i $BATCH_MAIN_CONF
 sed "s#@INSTALLED_HOSNAME@#`hostname`#g" -i  -i $BATCH_MAIN_CONF
 
 # logrotate:
-ln -sf $APP_DIR/configurations/logrotate/kaltura_batch /etc/logrotate.d/ 
-ln -sf $APP_DIR/configurations/logrotate/kaltura_apache /etc/logrotate.d/
-ln -sf $APP_DIR/configurations/logrotate/kaltura_apps /etc/logrotate.d/
+ln -sf $APP_DIR/configurations/logrotate/borhan_batch /etc/logrotate.d/ 
+ln -sf $APP_DIR/configurations/logrotate/borhan_apache /etc/logrotate.d/
+ln -sf $APP_DIR/configurations/logrotate/borhan_apps /etc/logrotate.d/
 if [ -x "`which php5enmod 2>/dev/null`" ];then
-	php5enmod zz-kaltura
+	php5enmod zz-borhan
 fi
-if [ -x /opt/kaltura/bin/php7enmod ];then
-	/opt/kaltura/bin/php7enmod zz-kaltura
+if [ -x /opt/borhan/bin/php7enmod ];then
+	/opt/borhan/bin/php7enmod zz-borhan
 fi
 
 mkdir -p $LOG_DIR/batch 
 find $BASE_DIR/app/cache/ $BASE_DIR/log -type d -exec chmod 775 {} \; 
 find $BASE_DIR/app/cache/ $BASE_DIR/log -type f -exec chmod 664 {} \; 
-chown $KALTURA_USER.$APACHE_GROUP $BASE_DIR/app/cache/ $BASE_DIR/log/* $WEB_DIR/content/entry $BASE_DIR/var/run
+chown $BORHAN_USER.$APACHE_GROUP $BASE_DIR/app/cache/ $BASE_DIR/log/* $WEB_DIR/content/entry $BASE_DIR/var/run
 
 if service apache2 status >/dev/null 2>&1;then
 	service apache2 reload
@@ -80,8 +80,8 @@ else
 	service apache2 start
 fi
 
-/etc/init.d/kaltura-batch stop >/dev/null 2>&1 || true
-/etc/init.d/kaltura-batch start
+/etc/init.d/borhan-batch stop >/dev/null 2>&1 || true
+/etc/init.d/borhan-batch start
 ln -sf $BASE_DIR/app/configurations/monit/monit.d/batch.rc /etc/monit/conf.d/
 ln -sf $BASE_DIR/app/configurations/monit/monit.d/httpd.rc /etc/monit/conf.d/apache2.rc
 ln -sf $BASE_DIR/app/configurations/monit/monit.d/memcached.rc /etc/monit/conf.d/
diff --git a/deb/kaltura-db/debian/postinst b/deb/kaltura-db/debian/postinst
--- a/deb/kaltura-db/debian/postinst
+++ b/deb/kaltura-db/debian/postinst
@@ -1,44 +1,44 @@
 #!/bin/bash -
 #===============================================================================
-#          FILE: kaltura-db-config.sh
-#         USAGE: ./kaltura-db-config.sh 
+#          FILE: borhan-db-config.sh
+#         USAGE: ./borhan-db-config.sh 
 #   DESCRIPTION: 
 #       OPTIONS: ---
 # 	LICENSE: AGPLv3+
 #  REQUIREMENTS: ---
 #          BUGS: ---
 #         NOTES: ---
-#        AUTHOR: Jess Portnoy, <jess.portnoy@kaltura.com>
-#  ORGANIZATION: Kaltura, inc.
+#        AUTHOR: Jess Portnoy, <jess.portnoy@borhan.com>
+#  ORGANIZATION: Borhan, inc.
 #       CREATED: 01/09/14 04:57:40 EST
 #      REVISION:  ---
 #===============================================================================
 #set -o nounset                              # Treat unset variables as an error
 
-deploy_kmc_and_studio()
+deploy_bmc_and_studio()
 {
 	HTML5_DIR=`ls -ld $BASE_DIR/web/html5/html5lib/v* 2>/dev/null|awk -F " " '{print $NF}' |tail -1`
 	HTML5_VER=`basename $HTML5_DIR`
 	HTML5_STUDIO_DIR=`ls -ld $BASE_DIR/apps/studio/v* 2>/dev/null|awk -F " " '{print $NF}' |tail -1`
 	HTML5_STUDIO_VER=`basename $HTML5_STUDIO_DIR`
 	if [ -f "$BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.template.ini" ];then
-		sed -e "s#@HTML5_STUDIO_VER@#$HTML5_STUDIO_VER#g" -e "s#@HTML5_VER@#$HTML5_VER#g" -e "s#@CDN_HOST@#$KALTURA_VIRTUAL_HOST_NAME#g" $BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.template.ini > $BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.ini		      
+		sed -e "s#@HTML5_STUDIO_VER@#$HTML5_STUDIO_VER#g" -e "s#@HTML5_VER@#$HTML5_VER#g" -e "s#@CDN_HOST@#$BORHAN_VIRTUAL_HOST_NAME#g" $BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.template.ini > $BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.ini		      
 	fi
 	if [ -r "$BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.ini" ];then
 		php $BASE_DIR/app/deployment/uiconf/deploy_v2.php --user=www-data --ini=$BASE_DIR/apps/studio/$HTML5_STUDIO_VER/studio.ini >> /dev/null
-		chown -R $APACHE_USER.$KALTURA_GROUP $WEB_DIR/content/generatedUiConf/
+		chown -R $APACHE_USER.$BORHAN_GROUP $WEB_DIR/content/generatedUiConf/
 		sed -i "s@^\(studio_version\s*=\)\(.*\)@\1 $HTML5_STUDIO_VER@g" -i $BASE_DIR/app/configurations/local.ini
 	fi
 
-	KMC_VERSION=`grep "^kmc_version" $APP_DIR/configurations/local.ini|awk -F "=" '{print $2}'|sed 's@\s*@@g'`
+	BMC_VERSION=`grep "^bmc_version" $APP_DIR/configurations/local.ini|awk -F "=" '{print $2}'|sed 's@\s*@@g'`
 	echo -e "${BRIGHT_BLUE}Generating UI confs..${NORMAL}"
-	php $APP_DIR/deployment/uiconf/deploy_v2.php --ini=$WEB_DIR/flash/kmc/$KMC_VERSION/config.ini --user=www-data >> $LOG_DIR/deploy_v2.log  2>&1
+	php $APP_DIR/deployment/uiconf/deploy_v2.php --ini=$WEB_DIR/flash/bmc/$BMC_VERSION/config.ini --user=www-data >> $LOG_DIR/deploy_v2.log  2>&1
 	STUDIO_VERSION=`grep "^studio_version" $APP_DIR/configurations/local.ini|awk -F "=" '{print $2}'|sed 's@\s*@@g'`
 	if [ -r "$BASE_DIR/apps/studio/$STUDIO_VERSION/studio.ini" ];then
 		echo -e "${BRIGHT_BLUE}Generating Studio UI confs..${NORMAL}"
 		php $APP_DIR/deployment/uiconf/deploy_v2.php --ini=$BASE_DIR/apps/studio/$STUDIO_VERSION/studio.ini --user=www-data >> $LOG_DIR/deploy_v2.log  2>&1
 	fi
-	chown -R www-data.kaltura $WEB_DIR/content
+	chown -R www-data.borhan $WEB_DIR/content
 	if [ -d $APP_DIR/deployment/updates/scripts/patches ];then
 		for i in $APP_DIR/deployment/updates/scripts/patches/*.sh;do
 			$i
@@ -52,21 +52,21 @@ deploy_kmc_and_studio()
 
 }
 
-RC_FILE=/etc/kaltura.d/system.ini
+RC_FILE=/etc/borhan.d/system.ini
 if [ ! -r "$RC_FILE" ];then
 	echo -e "${BRIGHT_RED}ERROR: could not find $RC_FILE so, exiting..${NORMAL}"
 	exit 2
 fi
 . $RC_FILE
-KALTURA_FUNCTIONS_RC=$BASE_DIR/bin/kaltura-functions.rc
-if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
-	echo "Could not find $KALTURA_FUNCTIONS_RC so, exiting.."
+BORHAN_FUNCTIONS_RC=$BASE_DIR/bin/borhan-functions.rc
+if [ ! -r "$BORHAN_FUNCTIONS_RC" ];then
+	echo "Could not find $BORHAN_FUNCTIONS_RC so, exiting.."
 	exit 3
 fi
-. $KALTURA_FUNCTIONS_RC
+. $BORHAN_FUNCTIONS_RC
 
 if [ -n "$2" ];then
-	deploy_kmc_and_studio
+	deploy_bmc_and_studio
 	exit $?
 fi
 
@@ -78,31 +78,31 @@ if [ "$1" = "configure" ]; then
 		exit 3
 	fi
 	. $DB_ACTIONS_RC
-	db_get 'kaltura-base/db_hostname'
+	db_get 'borhan-base/db_hostname'
 	DB1_HOST=$RET
 	if [ -z "$DB1_HOST" ];then
-		db_set 'kaltura-db/db_hostname' "`hostname`"
+		db_set 'borhan-db/db_hostname' "`hostname`"
 	else
-		db_set 'kaltura-db/db_hostname' $DB1_HOST
+		db_set 'borhan-db/db_hostname' $DB1_HOST
 	fi
-	db_input critical 'kaltura-db/db_hostname' || true
+	db_input critical 'borhan-db/db_hostname' || true
 	db_go || true
-	db_get 'kaltura-db/db_hostname'
+	db_get 'borhan-db/db_hostname'
 	MYSQL_HOST=$RET
 
-	db_input critical 'kaltura-db/db_port' || true
+	db_input critical 'borhan-db/db_port' || true
 	db_go || true
-	db_get 'kaltura-db/db_port'
+	db_get 'borhan-db/db_port'
 	MYSQL_PORT=$RET
 
-	db_input critical 'kaltura-db/mysql_super_user' || true
+	db_input critical 'borhan-db/mysql_super_user' || true
 	db_go || true
-	db_get 'kaltura-db/mysql_super_user'
+	db_get 'borhan-db/mysql_super_user'
 	MYSQL_SUPER_USER=$RET
 
-	db_input critical 'kaltura-db/mysql_super_passwd' || true
+	db_input critical 'borhan-db/mysql_super_passwd' || true
 	db_go || true
-	db_get 'kaltura-db/mysql_super_passwd'
+	db_get 'borhan-db/mysql_super_passwd'
 	MYSQL_SUPER_USER_PASSWD=$RET
 
 
@@ -116,7 +116,7 @@ if [ "$1" = "configure" ]; then
 		# the upgrade script is more complex naturally.. will include a check for schema
 		# decide how far back to run alter scripts, etc.
 	fi
-	KALTURA_DB=$DB1_NAME
+	BORHAN_DB=$DB1_NAME
 
 	# check DB connectivity:
 	echo -e "${CYAN}Checking MySQL version..${NORMAL}"
@@ -126,17 +126,17 @@ if [ "$1" = "configure" ]; then
 cat << EOF
 Failed to run:
 # mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT."
-Check your settings and run dpkg-reconfigure kaltura-db."
+Check your settings and run dpkg-reconfigure borhan-db."
 EOF
 		exit 4
 	fi
 	if ! check_mysql_settings $MYSQL_SUPER_USER $MYSQL_SUPER_USER_PASSWD $MYSQL_HOST $MYSQL_PORT ;then
 		if [ $MYSQL_HOST = 'localhost' -o $MYSQL_HOST = '127.0.0.1' ];then
-			db_input critical 'kaltura-db/fix_mysql_settings' || true
+			db_input critical 'borhan-db/fix_mysql_settings' || true
 			db_go || true
-			db_get 'kaltura-db/fix_mysql_settings'
+			db_get 'borhan-db/fix_mysql_settings'
 			if [ "$RET" = true ];then
-				$BASE_DIR/bin/kaltura-mysql-settings.sh
+				$BASE_DIR/bin/borhan-mysql-settings.sh
 			else
 				echo "Please adjust your settings manually and re-run." 
 				exit 8
@@ -147,15 +147,15 @@ EOF
 	fi
 	trap - ERR
 	if [ -z "$POPULATE_ONLY" ];then
-		# check whether the 'kaltura' already exists:
-		echo "use kaltura" | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT $KALTURA_DB 2> /dev/null
+		# check whether the 'borhan' already exists:
+		echo "use borhan" | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT $BORHAN_DB 2> /dev/null
 		if [ $? -eq 0 ];then
-			db_reset 'kaltura-db/db_already_installed'
-			db_input critical 'kaltura-db/db_already_installed' || true
+			db_reset 'borhan-db/db_already_installed'
+			db_input critical 'borhan-db/db_already_installed' || true
 			db_go || true
-			db_get 'kaltura-db/db_already_installed'
+			db_get 'borhan-db/db_already_installed'
 			if [ "$RET" = true ];then
-				$BASE_DIR/bin/kaltura-drop-db.sh $MYSQL_SUPER_USER_PASSWD
+				$BASE_DIR/bin/borhan-drop-db.sh $MYSQL_SUPER_USER_PASSWD
 			else
 				exit 0
 			fi
@@ -166,10 +166,10 @@ EOF
 		set -e
 
 		# create users:
-		USER_EXISTS=`echo "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = 'kaltura');" |  mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT`
+		USER_EXISTS=`echo "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = 'borhan');" |  mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT`
 		if [ "$USER_EXISTS" != "1" ];then	
-			echo "CREATE USER kaltura;"
-			echo "CREATE USER kaltura@'%' IDENTIFIED BY '$DB1_PASS' ;"  | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT
+			echo "CREATE USER borhan;"
+			echo "CREATE USER borhan@'%' IDENTIFIED BY '$DB1_PASS' ;"  | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT
 		fi
 		USER_EXISTS=`echo "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = 'etl');" |  mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT`
 		if [ "$USER_EXISTS" != "1" ];then	
@@ -191,7 +191,7 @@ EOF
 				mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT $DB < $SQL
 			done
 		done
-		echo "GRANT SELECT ON kaltura.* TO 'etl'@'%';FLUSH PRIVILEGES;" | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT
+		echo "GRANT SELECT ON borhan.* TO 'etl'@'%';FLUSH PRIVILEGES;" | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT
 
 		# DB schema created. Before we move onto populating, lets check MySQL and Sphinx connectivity.
 	fi
@@ -199,12 +199,12 @@ EOF
 
 	echo "Checking connectivity to needed daemons..."
 	if ! check_connectivity $DB1_USER $DB1_PASS $DB1_HOST $DB1_PORT $SPHINX_HOST $SERVICE_URL;then
-		db_reset 'kaltura-db/remove_db'
-		db_input critical 'kaltura-db/remove_db' || true
+		db_reset 'borhan-db/remove_db'
+		db_input critical 'borhan-db/remove_db' || true
 		db_go || true
-		db_get 'kaltura-db/remove_db'
+		db_get 'borhan-db/remove_db'
 		if [ "$RET" = true ];then
-			$BASE_DIR/bin/kaltura-drop-db.sh $MYSQL_SUPER_USER_PASSWD
+			$BASE_DIR/bin/borhan-drop-db.sh $MYSQL_SUPER_USER_PASSWD
 			exit 6
 		fi
 		exit 6
@@ -229,15 +229,15 @@ EOF
 		echo -e "${BRIGHT_RED}Please check your setup and then run $0 again.${NORMAL}"
 		exit 8
 	fi
-	db_get 'kaltura-front/is_apache_ssl'
+	db_get 'borhan-front/is_apache_ssl'
         IS_SSL="$RET"
 
 	if [ "$IS_SSL" = true ];then
-	# force KMC login via HTTPs.
+	# force BMC login via HTTPs.
 		php $APP_DIR/deployment/base/scripts/insertPermissions.php -d $APP_DIR/deployment/permissions/ssl/ > /dev/null 2>&1
 	fi
-	deploy_kmc_and_studio
-	rm -f $APP_DIR/log/kaltura-*.log
+	deploy_bmc_and_studio
+	rm -f $APP_DIR/log/borhan-*.log
 
 
 
